project:
  type: website
  output-dir: docs
  preview:
    port: 6879

website:
  title: "MAPPS 2023 Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
      - href: agenda.qmd
        text: Agenda
      - href: materials.qmd
    background: "#003C71"
    pinned: true

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    linkcolor: "#003C71"
