project:
  type: website
  output-dir: docs
  preview:
    port: 6879

website:
  title: "MAPPS 2023 Workshop"
  favicon: /images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
      - href: agenda.qmd
        text: Agenda
      - href: materials.qmd
    background: "#003C71"
    logo: /images/mapps-logo.png
    logo-alt: "MAPPS Logo"
    pinned: true

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    linkcolor: "#003C71"
