project:
  type: website

website:
  title: "MAPPS 2023 Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



