project:
  type: website
  output-dir: docs
  preview:
    port: 6879

website:
  title: "MAPPS 2023 Workshop"
  favicon: /images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guide.qmd
        text: Workshop Guide
      - href: slides.qmd
        text: Keynote Slides
      - href: dailies.qmd
        text: Daily Summaries
      - href: team.qmd
        text: The MAPPS Team
    background: "#003C71"
    logo: /images/mapps-logo.png
    logo-alt: "MAPPS Logo"
    pinned: true
  page-footer:
    left: "Copyright 2023, MAPPS"
    right: <img src='/images/icerm-logo.png' width='200px'>

format:
  html:
    theme:
      light: zephyr
    css: styles.css
    toc: true
    linkcolor: "#003C71"
